#pragma once
#include "CoreMinimal.h"
#include "EBtlDataSupportTable.generated.h"

UENUM(BlueprintType)
enum class EBtlDataSupportTable : uint8 {
    BTL_DATA_SUPPORT_ATK_UP,
    BTL_DATA_SUPPORT_ATK_DOWN,
    BTL_DATA_SUPPORT_ESC_UP,
    BTL_DATA_SUPPORT_ESC_DOWN,
    BTL_DATA_SUPPORT_DEF_UP,
    BTL_DATA_SUPPORT_DEF_DOWN,
    BTL_DATA_SUPPORT_HIT_UP,
    BTL_DATA_SUPPORT_HIT_DOWN,
    BTL_DATA_SUPPORT_HIRISK,
    BTL_DATA_SUPPORT_RISKHG,
    BTL_DATA_SUPPORT_AGINDA,
    BTL_DATA_SUPPORT_BUFNDA,
    BTL_DATA_SUPPORT_GALNDA,
    BTL_DATA_SUPPORT_JIONDA,
    BTL_DATA_SUPPORT_BADx2,
    BTL_DATA_SUPPORT_REDWALL,
    BTL_DATA_SUPPORT_BLUWALL,
    BTL_DATA_SUPPORT_YELWALL,
    BTL_DATA_SUPPORT_GRNWALL,
    BTL_DATA_SUPPORT_TETORA,
    BTL_DATA_SUPPORT_MAKARA,
    BTL_DATA_SUPPORT_BATKx2,
    BTL_DATA_SUPPORT_MATKx2,
    BTL_DATA_SUPPORT_DEKAJA,
    BTL_DATA_SUPPORT_DEKUNDA,
    BTL_DATA_SUPPORT_MAX UMETA(Hidden),
};

