#pragma once
#include "CoreMinimal.h"
#include "EBtlSceneAnimationType.generated.h"

UENUM(BlueprintType)
enum class EBtlSceneAnimationType : uint8 {
    BTL_S_ANIM_NULL,
    BTL_S_ANIM_ALLOUT_START_1,
    BTL_S_ANIM_ALLOUT_START_2,
    BTL_S_ANIM_ALLOUT_START_3,
    BTL_S_ANIM_ALLOUT_START_4,
    BTL_S_ANIM_ALLOUT_LAST,
    BTL_S_ANIM_SHUFFLE_START,
    BTL_S_ANIM_SHUFFLE_END,
    BTL_S_ANIM_SHUFFLE_LOOP,
    BTL_S_ANIM_TAKEOVER_FROM,
    BTL_S_ANIM_TAKEOVER_TO,
    BTL_S_ANIM_THEURGIA_A,
    BTL_S_ANIM_THEURGIA_B,
    BTL_S_ANIM_MIXRAID_A,
    BTL_S_ANIM_MIXRAID_B,
    BTL_S_ANIM_MIXRAID_C,
    BTL_S_ANIM_MIXRAID_D,
    BTL_S_ANIM_MIXRAID_E,
    BTL_S_ANIM_MIXRAID_F,
    BTL_S_ANIM_MIXRAID_G,
    BTL_S_ANIM_RESULT_MAIN,
    BTL_S_ANIM_RESULT_SUB,
    BTL_S_ANIM_SUMMON_LOOP,
    BTL_S_ANIM_SUMMON_ACT,
    BTL_S_ANIM_OVERHEAT_1,
    BTL_S_ANIM_OVERHEAT_2,
    BTL_S_ANIM_OVERHEAT_3,
    BTL_S_ANIM_THEURGIA_A_END,
    BTL_S_ANIM_MAX UMETA(Hidden),
};

