#pragma once
#include "CoreMinimal.h"
#include "EBtlDataAttr.generated.h"

UENUM(BlueprintType)
enum class EBtlDataAttr : uint8 {
    BTL_DATA_ATTR_SLASH,
    BTL_DATA_ATTR_STRIKE,
    BTL_DATA_ATTR_PIERCE,
    BTL_DATA_ATTR_FIRE,
    BTL_DATA_ATTR_ICE,
    BTL_DATA_ATTR_ELECTRIC,
    BTL_DATA_ATTR_WIND,
    BTL_DATA_ATTR_ALMIGHTY,
    BTL_DATA_ATTR_LIGHT,
    BTL_DATA_ATTR_DARK,
    BTL_DATA_ATTR_CHARM,
    BTL_DATA_ATTR_POISON,
    BTL_DATA_ATTR_UPSET,
    BTL_DATA_ATTR_PANIC,
    BTL_DATA_ATTR_FEAR,
    BTL_DATA_ATTR_ANGER,
    BTL_DATA_ATTR_RECOVERY,
    BTL_DATA_ATTR_SUPPORT,
    BTL_DATA_ATTR_SPECIAL,
    BTL_DATA_ATTR_NON,
    BTL_DATA_ATTR_MAX UMETA(Hidden),
};

