#pragma once
#include "CoreMinimal.h"
#include "ECommonAnimID.generated.h"

UENUM(BlueprintType)
enum class ECommonAnimID : uint8 {
    BLANK,
    Idel,
    Walk,
    Talk,
    SatMain,
    SatTalk,
    SatA,
    SatB,
    SatN,
    TurnL90,
    TurnR90,
    TurnL180,
    TurnR180,
    PhoneIdel,
    PhoneWalk,
    PhoneTalk,
    PhoneSatMain,
    PhoneSatTalk,
    StrongIdel,
    StrongWalk,
    StrongTalk,
    StrongSatMain,
    StrongSatTalk,
    WeakIdel,
    WeakWalk,
    WeakTalk,
    WeakSatMain,
    WeakSatTalk,
    FldAction1 = 0x32,
    FldAction2,
    FldAction3,
    FldAction4,
    FldAction5,
    FldAction6,
    FldAction7,
    FldAction8,
    FldAction9,
    FldAction10,
    FldAction11,
    FldAction12,
    FldAction13,
    FldAction14,
    FldAction15,
    FldAction16,
    FldAction17,
    FldAction18,
    FldAction19,
    TalkMainR = 0x50,
    TalkMainL,
    KageIdle = 0x64,
    DoorOpen1 = 0x73,
    DoorOpen2,
    DoorOpen3,
    DoorOpen4,
    DoorOpen5,
    DoorOpen6,
    DoorOpen7,
    DoorOpen8,
    DoorOpen9,
    DoorOpen10,
    DoorOpen11,
    DoorOpen12,
    PersonalAction1 = 0xC8,
    PersonalAction2,
    PersonalAction3,
    PersonalAction4,
    PersonalAction5,
    PersonalAction6,
    TurnL = 0xD2,
    TurnR,
};

