#pragma once
#include "CoreMinimal.h"
#include "EDungeonPathType.generated.h"

UENUM(BlueprintType)
enum class EDungeonPathType : uint8 {
    Blank,
    PartNiagara,
    Part,
    PartWall,
    FDoorPart,
    Environment,
    EffectNiagara,
    Effect,
    EnemyNiagara,
    Enemy,
    Enemy_Unique,
    Enemy_Boss,
    Enemy_FBD,
    TBoxNiagara,
    TBoxObj,
    TBox,
    TBoxSE,
    BrokenObjNiagara,
    BrokenObj,
    ReturnDev,
    Clock,
    SecretGate,
    CameraAttachNiagara,
    SupportSkill,
    Reaper,
    AutoRecover,
    Partner,
    Missing,
    MisNpcTypeSE,
    BfBmd,
    EnemyModel,
    BtlEnemyModel,
    UI,
    Sprite,
    EncountChara,
    BattleResident,
    BattleResidentBackLoad,
    BattleField,
    ParamData,
    Niagara,
    CheckMode,
    Num,
};

