#pragma once
#include "CoreMinimal.h"
#include "EEventAnimID.generated.h"

UENUM(BlueprintType)
enum class EEventAnimID : uint8 {
    BLANK,
    Main,
    Neutral,
    Walk,
    Run,
    TalkR,
    TalkMainR,
    SatN,
    SatMain,
    SatTalkR,
    TurnL90,
    TurnR90,
    TurnL180,
    TurnR180,
    NodN,
    NeckSwingN,
    BagL,
    TalkR_17,
    Main_18,
    TalkR_19,
    MainTag,
    NeutralTag,
    WalkTag,
    RunTag,
    TalkRTag,
    TalkMainRTag,
    SurprisedTag,
    AngryTag,
    TroubleTag,
    SadTag,
    CryTag,
    LaughTag,
    GladTag,
    StandingActionATag,
    SatActionTag,
    SatNTag,
    SatMainStartTag,
    SatMainTag,
    SatMainEndTag,
    SatAStartTag,
    SatATag,
    SatAEndTag,
    SatBStartTag,
    SatBTag,
    SatBEndTag,
    StandTag,
    SitTag,
    StandingAStartTag,
    StandingATag,
    StandingAEndTag,
    StandingBStartTag,
    StandingBTag,
    StandingBEndTag,
    StandingActionBTag,
    TalkSatNTag,
    EVC0321 = 0x3C,
    EVC0322,
};

