#pragma once
#include "CoreMinimal.h"
#include "EOkNextLayout.generated.h"

UENUM(BlueprintType)
enum class EOkNextLayout : uint8 {
    OK_DUNGEON_ITEM_OFFSET,
    OK_CAMP_HUMAN_PARAMETER_OFFSET,
    OK_CAMP_THEURGIA_OFFSET,
    OK_COMMU_POETRY_OFFSET,
    OK_COMMU_RANK_UP_OFFSET,
    OK_BATTLE_RESULT_OFFSET,
    BUTTON_BATTLE_RESULT_OFFSET,
    OK_SYSTEM_WINDOW_OFFSET,
    NEXT_CAMP_THEURGIA_OFFSET,
    NEXT_SYSTEM_WINDOW_OFFSET,
    OK_ONLY_CAMP_HUMAN_PARAMETER_OFFSET,
    YES_OFFSET,
    NO_OFFSET,
    Max,
};

