#pragma once
#include "CoreMinimal.h"
#include "EOkNextMaskLayout.generated.h"

UENUM(BlueprintType)
enum class EOkNextMaskLayout : uint8 {
    OK_DUNGEON_ITEM_MSK_SIZE,
    OK_DUNGEON_ITEM_MSK_OFFSET,
    OK_CAMP_HUMAN_PARA_MSK_SIZE,
    OK_CAMP_HUMAN_PARA_MSK_OFFSET,
    OK_CAMP_THEURGIA_MSK_SIZE,
    OK_CAMP_THEURGIA_MSK_OFFSET,
    OK_COMMU_POETRY_MSK_SIZE,
    OK_COMMU_POETRY_MSK_OFFSET,
    OK_COMMU_RANK_UP_MSK_SIZE,
    OK_COMMU_RANK_UP_MSK_OFFSET,
    OK_SYSTEM_WINDOW_MSK_SIZE,
    OK_SYSTEM_WINDOW_MSK_OFFSET,
    NEXT_CAMP_THEURGIA_MSK_SIZE,
    NEXT_CAMP_THEURGIA_MSK_OFFSET,
    NEXT_SYSTEM_WINDOW_MSK_SIZE,
    NEXT_SYSTEM_WINDOW_MSK_OFFSET,
    Max,
};

