#pragma once
#include "CoreMinimal.h"
#include "EUI_OT_TYPE.generated.h"

UENUM(BlueprintType)
enum class EUI_OT_TYPE : uint8 {
    EUI_Defult_Value,
    UI_OT_BEGIN = 0x0,
    UI_OT_BATTLE_LOW = 0x3,
    UI_OT_BATTLE_MIDDLE = 0x5,
    UI_OT_BATTLE_HIGH,
    UI_SKELETON_OT_2D_HIGH,
    UI_OT_FADE_UI_BACK = 0x9,
    UI_OT_UI_PANEL_BACK,
    UI_OT_UI_PANEL,
    UI_OT_UI_PANEL_FRONT,
    UI_OT_FACILITY,
    UI_OT_FACILITY_FRONT = 0x11,
    UI_OT_FCL_WEAPON,
    UI_OT_CAMP_BACK = 0x14,
    UI_OT_CAMP,
    UI_OT_CAMP_FRONT,
    UI_OT_CAMP_MORE_FRONT,
    UI_OT_PERSONA_STATUS_BACK,
    UI_OT_PERSONA_STATUS,
    UI_OT_PERSONA_STATUS_FRONT,
    UI_OT_SAVE,
    UI_OT_CAMP_WIPE = 0x1E,
    UI_OT_STAFFROLL,
    UI_OT_FADE,
    UI_OT_MESSAGE_WINDOW_BACK,
    UI_OT_BUSTUP,
    UI_OT_MESSAGE_WINDOW,
    UI_OT_MESSAGE_SEL_WINDOW,
    UI_OT_BACKLOG,
    UI_OT_CALENDAR,
    UI_OT_NETWORK,
    UI_OT_DEBUG = 0x29,
    UI_OT_NUM_MAX UMETA(Hidden),
    EUI_OT_MAX UMETA(Hidden),
};

