#pragma once
#include "CoreMinimal.h"
#include "EUIOTPRESET_BLEND_TYPE.generated.h"

UENUM(BlueprintType)
enum class EUIOTPRESET_BLEND_TYPE : uint8 {
    EUI_Defult_Value,
    UI_OT_PRESET_BLEND_OPAQUE = 0x0,
    UI_OT_PRESET_BLEND_SEMITRANS,
    UI_OT_PRESET_BLEND_ADDTRANS,
    UI_OT_PRESET_BLEND_SUBTRANS,
    UI_OT_PRESET_BLEND_MULTRANS,
    UI_OT_PRESET_BLEND_MUL2TRANS,
    UI_OT_PRESET_BLEND_ADVANCED,
    UI_OT_PRESET_BLEND_MAKE_MASK,
    UI_OT_PRESET_BLEND_MAKE_MASK_MUL,
    UI_OT_PRESET_BLEND_DRAW_ONLY_MASK,
    EUIOTPRESET_BLEND_MAX UMETA(Hidden),
};

